In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Data Preprocessing**

In [111]:
credit_card = pd.read_csv('UCI_Credit_Card.csv')
credit_card.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [112]:
# Drop ID
credit_card = credit_card.drop('ID', axis = 1)
credit_card.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [113]:
# One Hot Encoding on SEX variable
credit_card = pd.get_dummies(credit_card, columns = ['SEX'])
credit_card.head()

,LIMIT_BAL,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,...,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month,SEX_1,SEX_2
0,20000.0,2,1,24,2,2,-1,-1,-2,-2,...,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1,False,True
1,120000.0,2,2,26,-1,2,0,0,0,2,...,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1,False,True
2,90000.0,2,2,34,0,0,0,0,0,0,...,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0,False,True
3,50000.0,2,1,37,0,0,0,0,0,0,...,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0,False,True
4,50000.0,2,1,57,-1,0,-1,0,0,0,...,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0,True,False

In [114]:
# One Hot Encoding for EDUCATION variable but let's rename columns too
credit_card = pd.get_dummies(credit_card, columns = ['EDUCATION'])
credit_card = credit_card.drop('EDUCATION_0', axis = 1)
credit_card.head()

,LIMIT_BAL,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,PAY_AMT6,default.payment.next.month,SEX_1,SEX_2,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,EDUCATION_5,EDUCATION_6
0,20000.0,1,24,2,2,-1,-1,-2,-2,3913.0,...,0.0,1,False,True,False,True,False,False,False,False
1,120000.0,2,26,-1,2,0,0,0,2,2682.0,...,2000.0,1,False,True,False,True,False,False,False,False
2,90000.0,2,34,0,0,0,0,0,0,29239.0,...,5000.0,0,False,True,False,True,False,False,False,False
3,50000.0,1,37,0,0,0,0,0,0,46990.0,...,1000.0,0,False,True,False,True,False,False,False,False
4,50000.0,1,57,-1,0,-1,0,0,0,8617.0,...,679.0,0,True,False,False,True,False,False,False,False

In [115]:
# One Hot Encoding on MARRIAGE variable
credit_card = pd.get_dummies(credit_card, columns = ['MARRIAGE'])
credit_card.head()

,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,...,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,EDUCATION_5,EDUCATION_6,MARRIAGE_0,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3
0,20000.0,24,2,2,-1,-1,-2,-2,3913.0,3102.0,...,False,True,False,False,False,False,False,True,False,False
1,120000.0,26,-1,2,0,0,0,2,2682.0,1725.0,...,False,True,False,False,False,False,False,False,True,False
2,90000.0,34,0,0,0,0,0,0,29239.0,14027.0,...,False,True,False,False,False,False,False,False,True,False
3,50000.0,37,0,0,0,0,0,0,46990.0,48233.0,...,False,True,False,False,False,False,False,True,False,False
4,50000.0,57,-1,0,-1,0,0,0,8617.0,5670.0,...,False,True,False,False,False,False,False,True,False,False

In [116]:
credit_card.columns

Index(['LIMIT_BAL', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default.payment.next.month',
       'SEX_1', 'SEX_2', 'EDUCATION_1', 'EDUCATION_2', 'EDUCATION_3',
       'EDUCATION_4', 'EDUCATION_5', 'EDUCATION_6', 'MARRIAGE_0', 'MARRIAGE_1',
       'MARRIAGE_2', 'MARRIAGE_3'],
      dtype='object')

In [117]:
# scaling and train test split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Split first
X_temp = credit_card.drop('default.payment.next.month', axis=1)
y = credit_card['default.payment.next.month']

X_train, X_temp, y_train, y_temp = train_test_split(X_temp, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

# Scale only numerical features in TRAIN, then transform VAL & TEST
scaler = StandardScaler()

X_train_num = pd.DataFrame(scaler.fit_transform(X_train[numerical_columns]), columns=numerical_columns, index=X_train.index)
X_val_num = pd.DataFrame(scaler.transform(X_val[numerical_columns]), columns=numerical_columns, index=X_val.index)
X_test_num = pd.DataFrame(scaler.transform(X_test[numerical_columns]), columns=numerical_columns, index=X_test.index)

# Concatenate categorical features (already 0/1)
X_train_final = pd.concat([X_train_num, X_train[categorical_columns[1:]]], axis=1)  # exclude target col
X_val_final = pd.concat([X_val_num, X_val[categorical_columns[1:]]], axis=1)
X_test_final = pd.concat([X_test_num, X_test[categorical_columns[1:]]], axis=1)

# **Logistic Regression**

In [118]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, confusion_matrix

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_final, y_train)

y_pred_lr = logreg.predict(X_test_final)
y_prob_lr = logreg.predict_proba(X_test_final)[:, 1]

accuracy_lr = accuracy_score(y_test, y_pred_lr)
classification_report_lr = classification_report(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_prob_lr)
confusion_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print("-- Logistic Regression Results --")
print("\nAccuracy: ", accuracy_lr)
print("\nClassification Report: \n", classification_report_lr)
print("\nROC AUC Score: ", roc_auc_lr)
print("\nConfusion Matrix: \n", confusion_matrix_lr)

-- Logistic Regression Results --

Accuracy:  0.8093333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.97      0.89      3504
           1       0.71      0.24      0.35       996

    accuracy                           0.81      4500
   macro avg       0.76      0.60      0.62      4500
weighted avg       0.79      0.81      0.77      4500


ROC AUC Score:  0.7186230653206434

Confusion Matrix:
 [[3407   97]
 [ 761  235]]

# **Neural Network**

In [119]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, classification_report
from sklearn.utils.class_weight import compute_class_weight

weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights = {0: weights[0], 1: weights[1]}

nn_model = Sequential([Dense(64, input_dim=X_train_final.shape[1], activation='relu'), Dropout(0.2), Dense(32, activation='relu'), Dense(1, activation='sigmoid')])


nn_model.compile(optimizer = Adam(learning_rate = 0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])

history = nn_model.fit(X_train_final, y_train, validation_data = (X_val_final, y_val), epochs = 50, batch_size = 32, class_weight = class_weights)

y_prob_nn = nn_model.predict(X_test_final).flatten()
y_pred_nn = (y_prob_nn > 0.4).astype(int)

accuracy_nn = accuracy_score(y_test, y_pred_nn)
confusion_matrix_nn = confusion_matrix(y_test, y_pred_nn)
roc_auc_nn = roc_auc_score(y_test, y_pred_nn)
classification_report_nn = classification_report(y_test, y_pred_nn)

print("-- Neural Network Results --")
print("\nAccuracy: ", accuracy_nn)
print("\nClassification Report: \n", classification_report_nn)
print("\nROC AUC Score: ", roc_auc_nn)
print("\nConfusion Matrix: \n", confusion_matrix_nn)

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

657/657 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.6842 - loss: 0.6306 - val_accuracy: 0.7440 - val_loss: 0.5983
Epoch 2/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7525 - loss: 0.5824 - val_accuracy: 0.7542 - val_loss: 0.5724
Epoch 3/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7553 - loss: 0.5714 - val_accuracy: 0.7380 - val_loss: 0.5805
Epoch 4/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7601 - loss: 0.5620 - val_accuracy: 0.7333 - val_loss: 0.5795
Epoch 5/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7542 - loss: 0.5614 - val_accuracy: 0.7373 - val_loss: 0.5673
Epoch 6/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7535 - loss: 0.5581 - val_accuracy: 0.7053 - val_loss: 0.6111
Epoch 7/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7456 - loss: 0.5611 - val_accuracy: 0.7671 - val_loss: 0.5473
Epoch 8/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7620 - loss: 0.5496 - val_accuracy: 0.7620 - val_loss: 0.5460
Epoch 9/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7556 - loss: 0.5506 - val_accuracy: 0.7380 - val_loss: 0.5729
Epoch 10/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7469 - loss: 0.5608 - val_accuracy: 0.7402 - val_loss: 0.5648
Epoch 11/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7593 - loss: 0.5486 - val_accuracy: 0.7111 - val_loss: 0.5948
Epoch 12/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7446 - loss: 0.5630 - val_accuracy: 0.7553 - val_loss: 0.5571
Epoch 13/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7473 - loss: 0.5527 - val_accuracy: 0.7522 - val_loss: 0.5572
Epoch 14/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7518 - loss: 0.5520 - val_accuracy: 0.7449 - val_loss: 0.5654
Epoch 15/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7626 - loss: 0.5483 - val_accuracy: 0.7322 - val_loss: 0.5732
Epoch 16/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7509 - loss: 0.5487 - val_accuracy: 0.7313 - val_loss: 0.5660
Epoch 17/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7448 - loss: 0.5449 - val_accuracy: 0.7398 - val_loss: 0.5655
Epoch 18/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7581 - loss: 0.5494 - val_accuracy: 0.7364 - val_loss: 0.5638
Epoch 19/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7459 - loss: 0.5467 - val_accuracy: 0.7513 - val_loss: 0.5571
Epoch 20/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7522 - loss: 0.5421 - val_accuracy: 0.7418 - val_loss: 0.5607
Epoch 21/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7639 - loss: 0.5408 - val_accuracy: 0.7291 - val_loss: 0.5620
Epoch 22/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7426 - loss: 0.5423 - val_accuracy: 0.7349 - val_loss: 0.5831
Epoch 23/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7535 - loss: 0.5379 - val_accuracy: 0.7498 - val_loss: 0.5423
Epoch 24/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7557 - loss: 0.5363 - val_accuracy: 0.7416 - val_loss: 0.5663
Epoch 25/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7461 - loss: 0.5409 - val_accuracy: 0.7580 - val_loss: 0.5380
Epoch 26/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7525 - loss: 0.5388 - val_accuracy: 0.7329 - val_loss: 0.5648
Epoch 27/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7568 - loss: 0.5352 - val_accuracy: 0.7260 - val_loss: 0.5773
Epoch 28/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7535 - loss: 0.5329 - val_accuracy: 0.7267 - val_loss: 0.5720
Epoch 29/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7543 - loss: 0.5339 - val_accuracy: 0.7442 - val_loss: 0.5530
Epoch 30/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7575 - loss: 0.5357 - val_accuracy: 0.7342 - val_loss: 0.5520
Epoch 31/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7498 - loss: 0.5359 - val_accuracy: 0.7293 - val_loss: 0.5755
Epoch 32/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7494 - loss: 0.5347 - val_accuracy: 0.7431 - val_loss: 0.5534
Epoch 33/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7580 - loss: 0.5219 - val_accuracy: 0.7489 - val_loss: 0.5446
Epoch 34/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7513 - loss: 0.5323 - val_accuracy: 0.7331 - val_loss: 0.5729
Epoch 35/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7517 - loss: 0.5285 - val_accuracy: 0.7147 - val_loss: 0.5896
Epoch 36/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7539 - loss: 0.5273 - val_accuracy: 0.7102 - val_loss: 0.5953
Epoch 37/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7548 - loss: 0.5280 - val_accuracy: 0.7204 - val_loss: 0.5759
Epoch 38/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7536 - loss: 0.5202 - val_accuracy: 0.7438 - val_loss: 0.5481
Epoch 39/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7620 - loss: 0.5287 - val_accuracy: 0.7318 - val_loss: 0.5644
Epoch 40/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7578 - loss: 0.5231 - val_accuracy: 0.7338 - val_loss: 0.5661
Epoch 41/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7521 - loss: 0.5301 - val_accuracy: 0.7438 - val_loss: 0.5467
Epoch 42/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7517 - loss: 0.5263 - val_accuracy: 0.7402 - val_loss: 0.5578
Epoch 43/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7671 - loss: 0.5195 - val_accuracy: 0.7069 - val_loss: 0.5819
Epoch 44/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7459 - loss: 0.5336 - val_accuracy: 0.7376 - val_loss: 0.5615
Epoch 45/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7652 - loss: 0.5156 - val_accuracy: 0.7002 - val_loss: 0.5892
Epoch 46/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7475 - loss: 0.5298 - val_accuracy: 0.7409 - val_loss: 0.5464
Epoch 47/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7577 - loss: 0.5191 - val_accuracy: 0.7040 - val_loss: 0.5924
Epoch 48/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7569 - loss: 0.5142 - val_accuracy: 0.6929 - val_loss: 0.5884
Epoch 49/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7536 - loss: 0.5221 - val_accuracy: 0.7098 - val_loss: 0.5856
Epoch 50/50
657/657 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7500 - loss: 0.5275 - val_accuracy: 0.7220 - val_loss: 0.5643
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
-- Neural Network Results --

Accuracy:  0.6266666666666667

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.58      0.71      3504
           1       0.35      0.79      0.48       996

    accuracy                           0.63      4500
   macro avg       0.63      0.69      0.60      4500
weighted avg       0.78      0.63      0.66      4500


ROC AUC Score:  0.685177353248611

Confusion Matrix:
 [[2033 1471]
 [ 209  787]]

# **Export Model**

In [123]:
import pickle

with open('logreg_model.pkl', 'wb') as f:
    pickle.dump(logreg, f)

with open('nn_model.pkl', 'wb') as f:
    pickle.dump(nn_model, f)